
#[derive(Clone, Debug, PartialEq)]
pub struct RuleAction {
    action_type: RuleActionType,
    argument: Option<String>,
}

#[derive(Clone, Debug, PartialEq)]
pub enum RuleActionType {
    Accuracy,
    Allow,
    Append,
    AuditLog,
    Block,
    Capture,
    Chain,
    Ctl,
    Deny,
    DeprecateVar,
    Drop,
    Exec,
    ExpireVar,
    Id,
    InitCol,
    Log,
    LogData,
    Maturity,
    Msg,
    MultiMatch,
    NoAuditLog,
    Nolog,
    Pass,
    Pause,
    Phase,
    Prepend,
    Proxy,
    Redirect,
    Rev,
    SanitiseArg,
    SanitiseMatched,
    SanitiseMatchedBytes,
    SanitiseRequestHeader,
    SanitiseResponseHeader,
    Severity,
    Setuid,
    SetRsc,
    SetSid,
    SetEnv,
    SetVar,
    Skip,
    SkipAfter,
    Status,
    T,
    Tag,
    Ver,
    Xmlns,
}

impl std::convert::From<&str> for RuleActionType {
    fn from(input: &str) -> Self {
        match input {
            "accuracy" => RuleActionType::Accuracy,
            "allow" => RuleActionType::Allow,
            "append" => RuleActionType::Append,
            "auditlog" => RuleActionType::AuditLog,
            "block" => RuleActionType::Block,
            "capture" => RuleActionType::Capture,
            "chain" => RuleActionType::Chain,
            "ctl" => RuleActionType::Ctl,
            "deny" => RuleActionType::Deny,
            "deprecatevar" => RuleActionType::DeprecateVar,
            "drop" => RuleActionType::Drop,
            "exec" => RuleActionType::Exec,
            "expirevar" => RuleActionType::ExpireVar,
            "id" => RuleActionType::Id,
            "initcol" => RuleActionType::InitCol,
            "log" => RuleActionType::Log,
            "logdata" => RuleActionType::LogData,
            "maturity" => RuleActionType::Maturity,
            "msg" => RuleActionType::Msg,
            "multiMatch" => RuleActionType::MultiMatch,
            "noauditlog" => RuleActionType::NoAuditLog,
            "nolog" => RuleActionType::Nolog,
            "pass" => RuleActionType::Pass,
            "pause" => RuleActionType::Pause,
            "phase" => RuleActionType::Phase,
            "prepend" => RuleActionType::Prepend,
            "proxy" => RuleActionType::Proxy,
            "redirect" => RuleActionType::Redirect,
            "rev" => RuleActionType::Rev,
            "sanitiseArg" => RuleActionType::SanitiseArg,
            "sanitiseMatched" => RuleActionType::SanitiseMatched,
            "sanitiseMatchedBytes" => RuleActionType::SanitiseMatchedBytes,
            "sanitiseRequestHeader" => RuleActionType::SanitiseRequestHeader,
            "sanitiseResponseHeader" => RuleActionType::SanitiseResponseHeader,
            "severity" => RuleActionType::Severity,
            "setuid" => RuleActionType::Setuid,
            "setrsc" => RuleActionType::SetRsc,
            "setsid" => RuleActionType::SetSid,
            "setenv" => RuleActionType::SetEnv,
            "setvar" => RuleActionType::SetVar,
            "skip" => RuleActionType::Skip,
            "skipAfter" => RuleActionType::SkipAfter,
            "status" => RuleActionType::Status,
            "t" => RuleActionType::T,
            "tag" => RuleActionType::Tag,
            "ver" => RuleActionType::Ver,
            "xmlns" => RuleActionType::Xmlns,
            _ => unimplemented!("action not implemented")
        }
    }
}
