version: "3.0"
services:
  dvwa:
    image: vulnerables/web-dvwa
    ports:
      - "8000:80"
  yawaf:
    image: mcdobr/yawaf
    ports:
      - "9000:80"
    environment:
      - YAWAF_HOST=localhost
      - YAWAF_UPSTREAM=http://dvwa
      - YAWAF_PORT=80
    links:
      - dvwa
