version: "3.0"
services:
  dvwa:
    image: vulnerables/web-dvwa
    ports:
      - "8000:80"
  yawaf:
    image: mcdobr/yawaf
    ports:
      - "80:80"
    environment:
        - YAWAF_UPSTREAM=http://dvwa
    links:
      - dvwa
