#[derive(Clone, Debug, PartialEq)]
pub enum RuleVariable {
    Args,
    ArgsCombinedSize,
    ArgsGet,
    ArgsGetNames,
    ArgsNames,
    ArgsPost,
    ArgsPostNames,
    AuthType,
    Duration,
    Env,
    Files,
    FilesCombinedSize,
    FilesNames,
    FullRequest,
    FullRequestLength,
    FilesSizes,
    FilesTmpnames,
    FilesTmpContent,
    Geo,
    HighestSeverity,
    InboundDataError,
    MatchedVar,
    MatchedVars,
    MatchedVarName,
    MatchedVarsNames,
    ModsecBuild,
    MultipartCrlfLfLines,
    MultipartFilename,
    MultipartName,
    MultipartStrictError,
    MultipartUnmatchedBoundary,
    OutboundDataError,
    PathInfo,
    PerfAll,
    PerfCombined,
    PerfGc,
    PerfLogging,
    PerfPhase1,
    PerfPhase2,
    PerfPhase3,
    PerfPhase4,
    PerfPhase5,
    PerfRules,
    PerfSread,
    PerfSwrite,
    QueryString,
    RemoteAddr,
    RemoteHost,
    RemotePort,
    RemoteUser,
    ReqbodyError,
    ReqbodyErrorMsg,
    ReqbodyProcessor,
    RequestBasename,
    RequestBody,
    RequestBodyLength,
    RequestCookies,
    RequestCookiesNames,
    RequestFilename,
    RequestHeaders,
    RequestHeadersNames,
    RequestLine,
    RequestMethod,
    RequestProtocol,
    RequestUri,
    RequestUriRaw,
    ResponseBody,
    ResponseContentLength,
    ResponseContentType,
    ResponseHeaders,
    ResponseHeadersNames,
    ResponseProtocol,
    ResponseStatus,
    Rule,
    ScriptBasename,
    ScriptFilename,
    ScriptGid,
    ScriptGroupname,
    ScriptMode,
    ScriptUid,
    ScriptUsername,
    SdbmDeleteError,
    ServerAddr,
    ServerName,
    ServerPort,
    Session,
    Sessionid,
    StatusLine,
    StreamInputBody,
    StreamOutputBody,
    Time,
    TimeDay,
    TimeEpoch,
    TimeHour,
    TimeMin,
    TimeMon,
    TimeSec,
    TimeWday,
    TimeYear,
    Tx,
    UniqueId,
    UrlencodedError,
    Userid,
    UseragentIp,
    Webappid,
    WebserverErrorLog,
    Xml,
}

impl std::convert::From<&str> for RuleVariable {
    fn from(input: &str) -> Self {
        match input {
            "ARGS" => RuleVariable::Args,
            "ARGS_COMBINED_SIZE" => RuleVariable::ArgsCombinedSize,
            "ARGS_GET" => RuleVariable::ArgsGet,
            "ARGS_GET_NAMES" => RuleVariable::ArgsGetNames,
            "ARGS_NAMES" => RuleVariable::ArgsNames,
            "ARGS_POST" => RuleVariable::ArgsPost,
            "ARGS_POST_NAMES" => RuleVariable::ArgsPostNames,
            "AUTH_TYPE" => RuleVariable::AuthType,
            "DURATION" => RuleVariable::Duration,
            "ENV" => RuleVariable::Env,
            "FILES" => RuleVariable::Files,
            "FILES_COMBINED_SIZE" => RuleVariable::FilesCombinedSize,
            "FILES_NAMES" => RuleVariable::FilesNames,
            "FULL_REQUEST" => RuleVariable::FullRequest,
            "FULL_REQUEST_LENGTH" => RuleVariable::FullRequestLength,
            "FILES_SIZES" => RuleVariable::FilesSizes,
            "FILES_TMPNAMES" => RuleVariable::FilesTmpnames,
            "FILES_TMP_CONTENT" => RuleVariable::FilesTmpContent,
            "GEO" => RuleVariable::Geo,
            "HIGHEST_SEVERITY" => RuleVariable::HighestSeverity,
            "INBOUND_DATA_ERROR" => RuleVariable::InboundDataError,
            "MATCHED_VAR" => RuleVariable::MatchedVar,
            "MATCHED_VARS" => RuleVariable::MatchedVars,
            "MATCHED_VAR_NAME" => RuleVariable::MatchedVarName,
            "MATCHED_VARS_NAMES" => RuleVariable::MatchedVarsNames,
            "MODSEC_BUILD" => RuleVariable::ModsecBuild,
            "MULTIPART_CRLF_LF_LINES" => RuleVariable::MultipartCrlfLfLines,
            "MULTIPART_FILENAME" => RuleVariable::MultipartFilename,
            "MULTIPART_NAME" => RuleVariable::MultipartName,
            "MULTIPART_STRICT_ERROR" => RuleVariable::MultipartStrictError,
            "MULTIPART_UNMATCHED_BOUNDARY" => RuleVariable::MultipartUnmatchedBoundary,
            "OUTBOUND_DATA_ERROR" => RuleVariable::OutboundDataError,
            "PATH_INFO" => RuleVariable::PathInfo,
            "PERF_ALL" => RuleVariable::PerfAll,
            "PERF_COMBINED" => RuleVariable::PerfCombined,
            "PERF_GC" => RuleVariable::PerfGc,
            "PERF_LOGGING" => RuleVariable::PerfLogging,
            "PERF_PHASE1" => RuleVariable::PerfPhase1,
            "PERF_PHASE2" => RuleVariable::PerfPhase2,
            "PERF_PHASE3" => RuleVariable::PerfPhase3,
            "PERF_PHASE4" => RuleVariable::PerfPhase4,
            "PERF_PHASE5" => RuleVariable::PerfPhase5,
            "PERF_RULES" => RuleVariable::PerfRules,
            "PERF_SREAD" => RuleVariable::PerfSread,
            "PERF_SWRITE" => RuleVariable::PerfSwrite,
            "QUERY_STRING" => RuleVariable::QueryString,
            "REMOTE_ADDR" => RuleVariable::RemoteAddr,
            "REMOTE_HOST" => RuleVariable::RemoteHost,
            "REMOTE_PORT" => RuleVariable::RemotePort,
            "REMOTE_USER" => RuleVariable::RemoteUser,
            "REQBODY_ERROR" => RuleVariable::ReqbodyError,
            "REQBODY_ERROR_MSG" => RuleVariable::ReqbodyErrorMsg,
            "REQBODY_PROCESSOR" => RuleVariable::ReqbodyProcessor,
            "REQUEST_BASENAME" => RuleVariable::RequestBasename,
            "REQUEST_BODY" => RuleVariable::RequestBody,
            "REQUEST_BODY_LENGTH" => RuleVariable::RequestBodyLength,
            "REQUEST_COOKIES" => RuleVariable::RequestCookies,
            "REQUEST_COOKIES_NAMES" => RuleVariable::RequestCookiesNames,
            "REQUEST_FILENAME" => RuleVariable::RequestFilename,
            "REQUEST_HEADERS" => RuleVariable::RequestHeaders,
            "REQUEST_HEADERS_NAMES" => RuleVariable::RequestHeadersNames,
            "REQUEST_LINE" => RuleVariable::RequestLine,
            "REQUEST_METHOD" => RuleVariable::RequestMethod,
            "REQUEST_PROTOCOL" => RuleVariable::RequestProtocol,
            "REQUEST_URI" => RuleVariable::RequestUri,
            "REQUEST_URI_RAW" => RuleVariable::RequestUriRaw,
            "RESPONSE_BODY" => RuleVariable::ResponseBody,
            "RESPONSE_CONTENT_LENGTH" => RuleVariable::ResponseContentLength,
            "RESPONSE_CONTENT_TYPE" => RuleVariable::ResponseContentType,
            "RESPONSE_HEADERS" => RuleVariable::ResponseHeaders,
            "RESPONSE_HEADERS_NAMES" => RuleVariable::ResponseHeadersNames,
            "RESPONSE_PROTOCOL" => RuleVariable::ResponseProtocol,
            "RESPONSE_STATUS" => RuleVariable::ResponseStatus,
            "RULE" => RuleVariable::Rule,
            "SCRIPT_BASENAME" => RuleVariable::ScriptBasename,
            "SCRIPT_FILENAME" => RuleVariable::ScriptFilename,
            "SCRIPT_GID" => RuleVariable::ScriptGid,
            "SCRIPT_GROUPNAME" => RuleVariable::ScriptGroupname,
            "SCRIPT_MODE" => RuleVariable::ScriptMode,
            "SCRIPT_UID" => RuleVariable::ScriptUid,
            "SCRIPT_USERNAME" => RuleVariable::ScriptUsername,
            "SDBM_DELETE_ERROR" => RuleVariable::SdbmDeleteError,
            "SERVER_ADDR" => RuleVariable::ServerAddr,
            "SERVER_NAME" => RuleVariable::ServerName,
            "SERVER_PORT" => RuleVariable::ServerPort,
            "SESSION" => RuleVariable::Session,
            "SESSIONID" => RuleVariable::Sessionid,
            "STATUS_LINE" => RuleVariable::StatusLine,
            "STREAM_INPUT_BODY" => RuleVariable::StreamInputBody,
            "STREAM_OUTPUT_BODY" => RuleVariable::StreamOutputBody,
            "TIME" => RuleVariable::Time,
            "TIME_DAY" => RuleVariable::TimeDay,
            "TIME_EPOCH" => RuleVariable::TimeEpoch,
            "TIME_HOUR" => RuleVariable::TimeHour,
            "TIME_MIN" => RuleVariable::TimeMin,
            "TIME_MON" => RuleVariable::TimeMon,
            "TIME_SEC" => RuleVariable::TimeSec,
            "TIME_WDAY" => RuleVariable::TimeWday,
            "TIME_YEAR" => RuleVariable::TimeYear,
            "TX" => RuleVariable::Tx,
            "UNIQUE_ID" => RuleVariable::UniqueId,
            "URLENCODED_ERROR" => RuleVariable::UrlencodedError,
            "USERID" => RuleVariable::Userid,
            "USERAGENT_IP" => RuleVariable::UseragentIp,
            "WEBAPPID" => RuleVariable::Webappid,
            "WEBSERVER_ERROR_LOG" => RuleVariable::WebserverErrorLog,
            "XML" => RuleVariable::Xml,
            _ => unimplemented!("directive not implemented")
        }
    }
}