name: Docker Image CI

on:
  push:
    branches: [ main, feature/docker_action ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag yawaf:$(date +%s)